version: '3.5'
services:
  minio:
    build: minio
    image: weather_minio:1.0.0
    command: server --console-address ":9001" /weather_data
    environment:
      MINIO_ROOT_USER: 9Z939G61IPEV0WFHWIW1
      MINIO_ROOT_PASSWORD: krPc7XIcvXPCGnZpX1BtMnmWr4OaTzXqsH+50Jd6
    ports:
      - "83:9000"
      - "84:9001"
    networks:
      - weather_ntwrk
  db:
    build: postgresql
    image: weather_postgresql:1.0.0
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - weather_ntwrk
  pgadmin:
    build: pgadmin
    image: weather_pgadmin:1.0.0
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: server@myapp.de
      PGADMIN_DEFAULT_PASSWORD: postgres
    ports:
      - "82:80"
    networks:
      - weather_ntwrk

  swagger-ui:
    build: swagger-ui
    image: weather_swagger-ui:1.0.0
    ports:
      - "81:8080"
    networks:
      - weather_ntwrk

  weather-service:
    build: weather-service
    image: weather-service:1.0.0

    networks:
      - weather_ntwrk
    depends_on:
      - db

  proxy:
    build: proxy
    ports:
      - "80:80"
    networks:
      - weather_ntwrk
    depends_on:
      - weather-service

networks:
    weather_ntwrk:
      name: weather_ntwrk