openapi: 3.0.0
info:
  version: 1.0.0
  title: Мониторинг информации о погоде
  contact:
    name: SenlaWeather
    url: https://senlainc.com/

servers:
  - url: http://{host}:{port}
    description: custom server
    variables:
      host:
        description: host name
        default: localhost
      port:
        description: port value
        default: "8080"

tags:
  - name: "Погода"
    description: "Информация о наличии товаров"

paths:
  /api/weather/get/info:
    get:
      tags:
        - "Погода"
      summary: "Получить последнюю информацию по погоде"
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Weather'
        '400':
          $ref: '#/components/responses/Bad_Request'

  /api/weather/avr:
    get:
      tags:
        - "Погода"
      summary: Получить средние показатели о погоде по определенному промежутку дат 
      parameters:
        - in: query
          name: from
          schema:
            type: string
            pattern: 'dd-MM-yyyy'
            example: 19-03-2023
          description: С какой даты
          required: false
        - in: query
          name: to
          schema:
            type: string
            pattern: 'dd-MM-yyyy' 
            example: 20-03-2023
          description: По какую дату
          required: false
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Weather'         
        '400':
          $ref: '#/components/responses/Bad_Request'

components:
  requestBodies:
    CreateWeather:
      description: Тело для создания Погоды
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Avr_weather'

  responses:
    Bad_Request:
      description: Запрос некорректен. Сервер не может обработать запрос
      content:
        application/json:
          schema:
            oneOf:
              - type: array
                items:
                  $ref: '#/components/schemas/t_single_error_response'
              - $ref: '#/components/schemas/t_multiple_error_response'
          examples:
            t_single_error_response:
              value:
                - logref: error
                  message:  Запрос содержит некорретные данные. Измените запрос и отправьте его ещё раз
            t_multiple_error_response:
              value:
                logref: structured_error
                errors:
                  - field: time_unit
                    message: Поле должно быть положительным числом
    Unauthorized:
      description: Для выполнения запроса на данный адрес требуется передать токен авторизации
    Forbidden:
      description: Данному токенту авторизации запрещено выполнять запроса на данный адрес
    Internal_Server_Error:
      description: Внутренняя ошибка сервера. Сервер не смог корректно обработать запрос
      content:
        applicaion/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/t_single_error_response'
          example:
            - logref: error
              message:  Сервер не смог корректно обработать запрос. Пожалуйста обратитесь к администратору

  schemas:
    Weather:
      type: object
      description: Данные о погоде
      properties:
        temperatureC:
          type: number
          format: double
          example: 30.2
          description: "Температура по Цельсию"
        windMph:
          type: number
          format: double
          example: 20.2
          description: "Скорость ветра м/ч"
        pressureIn:
          type: number
          format: double
          example: 50.4
          description: "Давление"
        humidity:
          type: number
          format: int32
          example: 70
          description: "Влажность"   
        condition:
          type: string
          example: Clear
          description: "Описание погоды"
        location:
          type: string
          example: Minsk
          description: "Локация"    

    Avr_weather:
      type: object
      description: Усредненные данные о погоде за определенный период
      properties:
        average_temperatureC:
          type: number
          format: double
          example: 30.2
          description: "Температура по Цельсию"
        average_windMph:
          type: number
          format: double
          example: 20.2
          description: "Скорость ветра м/ч"
        average_pressureIn:
          type: number
          format: double
          example: 50.4
          description: "Давление"
        average_humidity:
          type: number
          format: int32
          example: 70
          description: "Влажность"   
        average_condition:
          type: string
          example: Clear
          description: "Описание погоды"
        average_location:
          type: string
          example: Minsk
          description: "Локация" 

    t_single_error_response:
      type: object
      description: Ошибка. Содержит общее описание ошибки
      required:
        - logref
        - message
      properties:
        logref:
          type: string
          description: Тип ошибки
          example: error
        message:
          description: Сообщение ошибки
          type: string
          example: Запрос содержит некорретные данные. Измените запрос и отправьте его ещё раз

    t_multiple_error_response:
      type: object
      description: Ошибка. Содержит описание ошибок со ссылками на поля сущности
      required:
        - logref
        - errors
      properties:
        logref:
          type: string
          description: Тип ошибки
        errors:
          description: Наименование ошибочного поля
          type: array
          items:
            type: object
            properties:
              message:
                type: string
                description: Сообщение об ошибке
                example: Поле должно быть положительным числом
              field:
                type: string
                description: Наименование ошибочного поля
                example: time_unit